let easy = [
    "TITLE",
    "LAPTOP",
    "LIBRARY",
    "OPENER",
    "MOBILE",
    "TELEPHONE",
    "RANDOM",
    "CODING",
    "WIRES",
    "NETWORK",
    "GUITAR",
    "MUSIC",
    "KEYBOARD",
    "SCREEN",
    "PRINTER",
    "PENCIL",
    "PAPER",
    "MONITOR",
    "SPEAKER",
    "HEADPHONE",
    "SUNGLASSES",
    "UMBRELLA",
    "VACUUM",
    "JUICE",
    "CLOCK",
    "BACKPACK",
    "CAMERA",
    "MICROPHONE",
    "TELEVISION",
    "EARRINGS",
    "BRUSH",
    "MIRROR",
    "BICYCLE",
    "MAGAZINE",
    "JOURNAL",
    "KEYCHAIN",
    "CLOCK",
    "LAMP",
    "CUP",
    "GLASSES",
    "CANDY",
    "BOOK",
    "GLOBE",
    "SHOES",
    "COFFEE",
    "WALLET",
    "HAT",
    "CANDLE",
    "RING",
    "CHAIR",
    "DOOR",
    "WINDOW",
    "BAG",
    "WATER",
    "COW",
    "DOG",
    "CAT",
    "HORSE",
    "BIRD",
    "FISH",
    "TIGER",
    "ELEPHANT",
    "ZEBRA",
    "GIRAFFE",
    "MONKEY",
    "SNAKE",
    "LION",
    "BEAR",
    "KANGAROO",
    "RHINOCEROS",
    "CROCODILE",
    "BUTTERFLY",
    "SPIDER",
    "DRAGONFLY",
    "ANT",
    "LADYBUG",
    "MOSQUITO",
    "BEE",
    "FROG",
    "TURTLE",
    "CATERPILLAR",
    "STAR",
    "PLANET",
    "SATELLITE",
    "ASTRONAUT",
    "COMET",
    "GALAXY",
    "METEOR",
    "TELESCOPE",
    "ROCKET",
    "MOON",
    "SUN",
    "EARTH",
    "MARS",
    "VENUS",
    "JUPITER",
    "NEPTUNE",
    "PLUTO",
    "MERCURY",
    "SATURN",
    
];

let easy_hints = [
    "A name or heading",
    "Portable computer",
    "Place to borrow books",
    "Used to open bottles",
    "Another word for a cell phone",
    "An older communication device",
    "Lacks a pattern",
    "Writing code",
    "Cables",
    "Connects devices",
    "Stringed musical instrument",
    "Sound produced by instruments",
    "Input device for typing",
    "Display for computers",
    "Device for producing printed copies",
    "Used for writing or drawing",
    "Material for writing or drawing",
    "Display for computers",
    "Output device for sound",
    "Audio output for personal use",
    "Eyewear to protect eyes from the sun",
    "Protection from rain",
    "Cleaning appliance",
    "Fruit juice",
    "Timekeeping device",
    "Carry-on bag for books and supplies",
    "Capture device for images",
    "Audio input device",
    "Entertainment device",
    "Jewelry for ears",
    "Tool for grooming hair",
    "Reflective surface",
    "Two-wheeled vehicle",
    "Printed periodical",
    "Personal writing book",
    "Small item for holding keys",
    "Timekeeping device",
    "Illumination source",
    "Container for beverages",
    "Visual aid for eyesight correction",
    "Sweet treat",
    "Reading material",
    "Geographical representation",
    "Footwear",
    "Beverage made from roasted beans",
    "Carry-on accessory for money and cards",
    "Head covering",
    "Light source for decoration",
    "Circular jewelry",
    "Seating furniture",
    "Entryway barrier",
    "Opening for light and air",
    "Carry-on container",
    "Essential for life",
    "Mammal with spots",
    "Common domestic pet",
    "Domesticated feline",
    "Large mammal for riding",
    "Feathered creature",
    "Aquatic animal",
    "Large striped feline",
    "Giant land mammal",
    "Striped equine",
    "Tall spotted mammal",
    "Tree-dwelling primate",
    "Slithery reptile",
    "King of the jungle",
    "Large furry creature",
    "Hopping marsupial",
    "Horned land mammal",
    "Scaly reptile",
    "Colorful insect",
    "Eight-legged arachnid",
    "Flying insect",
    "Tiny insect",
    "Small flying insect",
    "Hoppy amphibian",
    "Slow-moving reptile",
    "Crawling larval insect",
    "Luminous celestial object",
    "Celestial body in space",
    "Man-made space object",
    "Space explorer",
    "Celestial object with a tail",
    "Vast collection of stars and dust",
    "Falling space rock",
    "Astronomical observing tool",
    "Space launch vehicle",
    "Earth's natural satellite",
    "Center of our solar system",
    "Planet we inhabit",
    "Red planet",
    "Second planet from the sun",
    "Largest planet in the solar system",
    "Distant ice giant",
    "Dwarf planet",
    "Closest planet to the sun",
    "Ringed gas giant",
];
